### ISSUE TITLE
Error while trying to add OData Service

### ISSUE THREAD

**Issue by signix** [ui5-community/generator-ui5-ts-app-fcl#10]
Using node v20.9.0 I have an error when trying to add an OData service.

https://ODATA_SERVICE_URL/TypeError: entityType.Property.map is not a function

Which endpoint do you want to use for your OData service? https://services.odata.org/TripPinRESTierService/TypeError: entityType.Property.map is not a function.

Is it related to node version ?

![image](https://github.com/ui5-community/generator-ui5-ts-app-fcl/assets/6778092/5974407a-b1c3-4213-bc1a-68aea9a6bf64)

**Comment by akudev** [comment]
@signix No, this is rather related to something special in the service definition, a case which has not been handled so far. I think the original code intended to handle it, but had a brace misplaced.
Fixed. Thanks for reporting!
